# Generated by Django 5.2.4 on 2025-07-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_supervisor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
